#!/bin/bash -e

. git-hooks/hook-lib.sh

stage Checking

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
checking whitespace
git diff-index --check --cached $against --
ok

if check_if_installed flake8; then
    (cd fallout-cli && flake8)
    ok
fi

if check_if_installed shellcheck; then
    git diff-index -z --name-only --cached $against -- | \
      _xargs -0 grep -E --null --files-with-matches '^#!.*/(env )?(ba|z|k)?sh\b' |
      _xargs -0 shellcheck -x --format=gcc
    ok
fi

checking gradle spotlessCheck
./gradlew -q spotlessCheck
ok
