apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: chaos-daemon
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: chaos-daemon
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: chaos-daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: chaos-daemon
    {{- with .Values.chaosDaemon.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
  {{- if .Values.chaosDaemon.hostNetwork }}
      hostNetwork: true
  {{- end }}
      hostIPC: true
      hostPID: true
      containers:
        - name: chaos-daemon
          image: {{ .Values.chaosDaemon.image }}
          imagePullPolicy: {{ .Values.chaosDaemon.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.chaosDaemon.resources }}
          resources:
{{ toYaml .Values.chaosDaemon.resources | indent 12 }}
          {{- end }}
          command:
            - /usr/local/bin/chaos-daemon
            - --runtime
            - {{ .Values.chaosDaemon.runtime }}
            - --http-port
            - !!str {{ .Values.chaosDaemon.httpPort }}
            - --grpc-port
            - !!str {{ .Values.chaosDaemon.grpcPort }}
          {{- if .Values.enableProfiling }}
            - --pprof
          {{- end }}
          env:
            {{- range $envKey, $envVal := .Values.chaosDaemon.env }}
            - name: {{ $envKey | upper }}
              value: {{ $envVal | quote }}
            {{- end }}
            {{- if not .Values.chaosDaemon.env.TZ }}
            - name: TZ
              value: {{ .Values.timezone | default "UTC" }}
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - NET_ADMIN
                - MKNOD
                - SYS_CHROOT
                - SYS_ADMIN
                - KILL
                # CAP_IPC_LOCK is used to lock memory
                - IPC_LOCK
          volumeMounts:
            - name: socket-path
              {{- if eq .Values.chaosDaemon.runtime "docker" }}
              mountPath: /var/run/docker.sock
              {{- else if eq .Values.chaosDaemon.runtime "containerd" }}
              mountPath: /run/containerd/containerd.sock
              {{- end }}
            - name: sys-path
              mountPath: /sys
          ports:
            - name: grpc
              containerPort: {{ .Values.chaosDaemon.grpcPort }}
              hostPort: {{ .Values.chaosDaemon.grpcPort }}
            - name: http
              containerPort: {{ .Values.chaosDaemon.httpPort }}
      {{- with .Values.chaosDaemon.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.bpfki.create }}
        - name: bpfki
          image: {{ .Values.bpfki.image }}
          imagePullPolicy: {{ .Values.bpfki.imagePullPolicy | default "IfNotPresent" }}
          {{- if .Values.bpfki.resources }}
          resources:
{{ toYaml .Values.bpfki.resources | indent 12 }}
          {{- end }}
          command:
            - /usr/local/bin/bpfki
            - -port
            - !!str {{ .Values.bpfki.grpcPort }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: localtime-path
              mountPath: /etc/localtime
              readOnly: true
            - name: modules-path
              mountPath: /lib/modules
              readOnly: true
            - name: src-path
              mountPath: /usr/src
              readOnly: true
          ports:
            - name: grpc
              containerPort: {{ .Values.bpfki.grpcPort }}
              hostPort: {{ .Values.bpfki.grpcPort }}
{{- end }}
      volumes:
        - name: socket-path
          hostPath:
            path: {{ .Values.chaosDaemon.socketPath | default "/var/run/docker.sock" }}
        - name: sys-path
          hostPath:
            path: /sys
{{- if .Values.bpfki.create }}
        - name: localtime-path
          hostPath:
            path: /etc/localtime
        - name: modules-path
          hostPath:
            path: /lib/modules
        - name: src-path
          hostPath:
            path: /usr/src
{{- end }}
