apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "chaos-mesh.svc" . }}
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  type: {{ .Values.controllerManager.service.type }}
  ports:
  {{- if .Values.enableProfiling }}
    - port: 10081
      targetPort: pprof
      protocol: TCP
      name: pprof
  {{- end }}
    - port: 10080
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
