apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: chaos-controller-manager
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.controllerManager.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller-manager
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    {{- with .Values.controllerManager.podAnnotations }}
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
    {{- if .Values.controllerManager.hostNetwork }}
      hostNetwork: true
    {{- end }}
    {{- if .Values.controllerManager.serviceAccount }}
      serviceAccount: {{ .Values.controllerManager.serviceAccount }}
    {{- end }}
      containers:
      - name: chaos-mesh
        image: {{ .Values.controllerManager.image }}
        imagePullPolicy: {{ .Values.controllerManager.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.controllerManager.resources | indent 12 }}
        command:
          - /usr/local/bin/chaos-controller-manager
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TEMPLATE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TARGET_NAMESPACE
            value: {{ .Values.controllerManager.targetNamespace }}
          - name: CLUSTER_SCOPED
            value: "{{ .Values.clusterScoped }}"
          - name: TZ
            value: {{ .Values.timezone | default "UTC" }}
          - name: CHAOS_DAEMON_PORT
            value: !!str {{ .Values.chaosDaemon.grpcPort }}
          - name: BPFKI_PORT
            value: !!str {{ .Values.bpfki.grpcPort }}
          - name: TEMPLATE_LABELS
            value: "app.kubernetes.io/component:template"
          - name: CONFIGMAP_LABELS
            value: "app.kubernetes.io/component:webhook"
          {{- if .Values.controllerManager.allowedNamespaces }}
          - name: ALLOWED_NAMESPACES
            value: {{ .Values.controllerManager.allowedNamespaces }}
          {{- end }}
          {{- if .Values.controllerManager.ignoredNamespaces }}
          - name: IGNORED_NAMESPACES
            value: {{ .Values.controllerManager.ignoredNamespaces }}
          {{- end }}
          {{- if .Values.enableProfiling }}
          - name: PPROF_ADDR
            value: ":10081"
          {{- end }}
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
        ports:
          - name: webhook
            containerPort: 9443 # Customize containerPort
          - name: http
            containerPort: 10080
        {{- if .Values.enableProfiling }}
          - name: pprof
            containerPort: 10081
        {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ template "chaos-mesh.certs" . }}
    {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controllerManager.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.controllerManager.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
