{{- if .Values.prometheus.create }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: chaos-prometheus
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- end }}
