#!/bin/bash

name="${1?no name}"
shift

filename="${1?no filename}"
shift

cat <<EOF
<testsuite name="$name">
<testcase file="$name" classname="$name" name="output">
EOF

[[ -s "$filename" ]] && cat <<EOF
<failure><![CDATA[
EOF

cat "$filename"

[[ -s "$filename" ]] && cat <<EOF
]]></failure>
EOF

cat <<EOF
</testcase>
</testsuite>
EOF
