apiVersion: v1
kind: Pod
metadata:
  name: artifact-collection-pod-{{pv-name}}
  labels:
    app: fallout-artifact-collection
spec:
  volumes:
    - name: fallout-artifacts
      persistentVolumeClaim:
        claimName: {{pvc-name}}
  containers:
    - name: {{container-name}}
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - >
          ls -R /fallout-artifacts;
          tail -f /dev/null;
      volumeMounts:
        - mountPath: "/fallout-artifacts"
          name: fallout-artifacts
  # remove grace period so kubernetes doesn't wait for the tail to finish before terminating the pod
  terminationGracePeriodSeconds: 0
