apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{pvc-name}}
spec:
  storageClassName: fallout-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{pv-capacity}}
  volumeName: {{pv-name}}
